name: 'build'
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add badges
        uses: rocktimsaikia/badge-it@master
        with:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          badges: 'license,version,github_stars'
          badge_style: 'flat-square'